---
- name: Install
  ansible.builtin.package:
    name:
      - conky
    state: latest
  become: yes
- name: conky.dir
  file:
    path: "{{ ansible_user_dir }}/.config/conky/"
    state: directory
- name: Configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/conky/conky.conf"
    src: "conky.conf"
- name: Startup Script
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/conky/startup.sh"
    src: "startup.sh"
    mode: "777"