---
- name: i3dir
  file:
    path: "{{ ansible_user_dir }}/.config/regolith/i3/"
    state: directory
- name: i3 Configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/regolith/i3/config"
    src: "i3config"
- name: i3xrocks_dir
  file:
    path: "{{ ansible_user_dir }}/.config/regolith/i3xrocks/"
    state: directory
- name: i3xrocks Configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/regolith/i3xrocks/conf.d"
    src: "conf.d/"
- name: XResources Configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/regolith/Xresources"
    src: "Xresources"
- name: rofi.dir
  file:
    path: "{{ ansible_user_dir }}/.config/rofi"
    state: directory
- name: rofi config
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/rofi/config.rasi"
    src: "config.rasi"
