---
- name: i3 Configuration
  vars:
    i3_dest_path: "{{ ansible_user_dir }}/.config/regolith/i3/config"
  tasks:
    - name: Make sure destination dir exists
      file:
        path: "{{ i3_dest_path | dirname }}"
        state: directory
    - name: Copy i3 file
      ansible.builtin.copy:
        dest: i3_dest_path
        src: "i3config"
- name: i3xrocks Configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/regolith/i3xrocks/conf.d"
    src: "conf.d/"
- name: XResources Configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/regolith/Xresources"
    src: "Xresources"

